let testHomeSSID = "Example-Home-WiFi"
import Foundation
expect(HomeSettings.defaultSSID.isEmpty && HomeSettings.defaultIP.isEmpty, "new installations require setup")
func expect(_ value: Bool, _ message: String) { if !value { fatalError(message) } }
var p = NetworkPolicy()
expect(p.observe(ssid: "Example-Home-WiFi", homeSSID: testHomeSSID, enabled: true) == nil, "debounce home")
expect(p.observe(ssid: "Example-Home-WiFi", homeSSID: testHomeSSID, enabled: true) == .home, "home mode")
expect(p.observe(ssid: nil, homeSSID: testHomeSSID, enabled: true) == nil, "unknown is not away")
expect(p.observe(ssid: "Cafe", homeSSID: testHomeSSID, enabled: true) == nil, "debounce away")
expect(p.observe(ssid: "Cafe", homeSSID: testHomeSSID, enabled: true) == .dhcp, "away restores DHCP")
expect(p.observe(ssid: "Example-Home-WiFi", homeSSID: testHomeSSID, enabled: false) == nil, "paused")
expect(p.observe(ssid: "Example-Home-WiFi", homeSSID: testHomeSSID, enabled: true) == nil, "pause resets debounce")
expect(p.observe(ssid: "", homeSSID: testHomeSSID, enabled: true) == nil, "empty is unknown")
expect(p.observe(ssid: "Example-Home-WiFi-Guest", homeSSID: testHomeSSID, enabled: true) == nil, "exact match debounce")
expect(p.observe(ssid: "Example-Home-WiFi-Guest", homeSSID: testHomeSSID, enabled: true) == .dhcp, "no prefix match")
print("Policy tests passed (10 checks)")
expect(!SpeakerPolicy.shouldMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true), "home leaves sound alone")
expect(SpeakerPolicy.shouldMute(ssid: "Cafe", homeSSID: testHomeSSID, enabled: true), "away mutes")
expect(SpeakerPolicy.shouldMute(ssid: nil, homeSSID: testHomeSSID, enabled: true), "unknown protects speakers")
expect(SpeakerPolicy.shouldMute(ssid: "", homeSSID: testHomeSSID, enabled: true), "disconnected protects speakers")
expect(SpeakerPolicy.shouldMute(ssid: testHomeSSID + "-Guest", homeSSID: testHomeSSID, enabled: true), "speaker home match is exact")
expect(!SpeakerPolicy.shouldMute(ssid: "Cafe", homeSSID: testHomeSSID, enabled: false), "independent protection switch")
expect(!SpeakerPolicy.shouldMute(ssid: nil, homeSSID: testHomeSSID, enabled: false), "disabled never acts")
expect(SpeakerPolicy.isInternalSpeaker(transport: 1651274862, source: 1769173099), "this Mac internal speakers")
expect(!SpeakerPolicy.isInternalSpeaker(transport: 0x626C746E, source: 0x6864706E), "wired headphones excluded")
expect(!SpeakerPolicy.isInternalSpeaker(transport: 0x626C7565, source: 0x6973706B), "Bluetooth excluded")
expect(!SpeakerPolicy.isInternalSpeaker(transport: 0x68646D69, source: 0x6973706B), "HDMI excluded")
expect(!SpeakerPolicy.isInternalSpeaker(transport: nil, source: nil), "unidentified devices excluded")
print("Speaker policy tests passed (12 checks)")
var transition = SpeakerTransitionPolicy()
expect(transition.desiredMute(ssid: "Cafe", homeSSID: testHomeSSID, enabled: true) == true, "away enforces mute")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == nil, "first home observation waits")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == false, "arrival restores sound")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == false, "failed restore retries")
transition.didRestoreHome()
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == nil, "manual mute at home is respected")
expect(transition.desiredMute(ssid: nil, homeSSID: testHomeSSID, enabled: true) == true, "unknown mutes and rearms")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == nil, "return waits again")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == false, "second return restores again")
transition.didRestoreHome()
expect(transition.desiredMute(ssid: nil, homeSSID: testHomeSSID, enabled: false) == nil, "disabled does not act")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == nil, "reenabling confirms home")
expect(transition.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == false, "reenabling restores home")
var startup = SpeakerTransitionPolicy()
expect(startup.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == nil, "startup home confirms")
expect(startup.desiredMute(ssid: testHomeSSID, homeSSID: testHomeSSID, enabled: true) == false, "startup home unmutes")
expect(startup.desiredMute(ssid: testHomeSSID + "-Guest", homeSSID: testHomeSSID, enabled: true) == true, "similar SSID mutes")
expect(startup.desiredMute(ssid: "", homeSSID: testHomeSSID, enabled: true) == true, "empty SSID mutes")
print("Home restoration tests passed (15 checks)")

expect(HomeSettings.validSSID("My Home"), "custom SSID accepted")
expect(HomeSettings.validSSID("家庭 Wi-Fi"), "Unicode SSID accepted")
expect(!HomeSettings.validSSID(""), "empty SSID rejected")
expect(!HomeSettings.validSSID("a\n"), "control characters rejected")
expect(!HomeSettings.validSSID(String(repeating: "a", count: 33)), "SSID length checked")
expect(HomeSettings.validIP("192.168.50.42"), "private IPv4 accepted")
expect(HomeSettings.validIP("10.0.0.42"), "custom IP accepted")
for value in ["192.168.1.0", "192.168.1.255", "127.0.0.1", "224.0.0.1", "192.168.1", "192.168.001.2", "192.168.1.2;reboot", "192.168.1.-1"] {
    expect(!HomeSettings.validIP(value), "invalid IP rejected: \(value)")
}
var custom = NetworkPolicy()
expect(custom.observe(ssid: "My Home", homeSSID: "My Home", enabled: true) == nil, "custom home debounce")
expect(custom.observe(ssid: "My Home", homeSSID: "My Home", enabled: true) == .home, "custom home mode")
var customSound = SpeakerTransitionPolicy()
expect(customSound.desiredMute(ssid: "My Home", homeSSID: "My Home", enabled: true) == nil, "custom home sound debounce")
expect(customSound.desiredMute(ssid: "My Home", homeSSID: "My Home", enabled: true) == false, "custom home restores sound")
expect(SpeakerPolicy.shouldMute(ssid: "Other", homeSSID: "My Home", enabled: true), "custom home excludes other SSID")
print("Custom settings tests passed")
